### ISSUE TITLE
Flamegraph not displaying properly, certain parts not clickable, displaying NaNs in sidebar

### ISSUE THREAD

**Issue by sgbaird** [P403n1x87/austin-vscode#32]
https://www.screencast.com/t/9Nh4fbZ43hK

I used the command palette to "Profile with Austin". Using Windows 11, VS Code 1.69.2, Austin VS Code `v.10.8`, latest Austin version via `choco install austin`.

![image](https://user-images.githubusercontent.com/45469701/181867505-f8b8e254-b6b3-465b-b8ee-1ffd9f3dafab.png)

**Comment by P403n1x87** [comment]
@sgbaird thanks for all the details. May I ask whether the OUTPUT panel or the Console log in the Developer Tools show any errors? Would you be able to check whether running Austin from the command line and then opening the output file in VS Code would result in the same problem? If so, it would be great if you could attach the file to see whether this is caused by bad samples. 🙇

**Comment by sgbaird** [comment]
@P403n1x87 I probably should have asked originally, but I was having trouble finding where the sample files are stored. I looked through my project folder and `C:\Program Files\P403n1x87\Austin`. Do you know where I should look for these?

The (Austin) Output panel shows output that I'd expect from my program running:
```python
...
Decoding objects from C:\Users\sterg\Miniconda3\envs\matbench-genmetrics\lib\site-packages\mp_time_split\utils\mp_time_summary.json.gz: 100%|##########| 40476/40476 [00:38<00:00, 1043.17it/s]

100%|##########| 5/5 [34:38<00:00, 483.38s/it]
100%|##########| 5/5 [34:38<00:00, 415.66s/it]
```

Here are a few snippets from the Console log (Ctrl + Shift + I for developer tools in case someone else comes across this). Not sure how relevant these are.

```python
804workbench.desktop.main.js:602   ERR Invalid string length: RangeError: Invalid string length
    at Socket.<anonymous> (c:\Users\sterg\.vscode\extensions\p403n1x87.austin-vscode-0.10.8\out\providers\executor.js:47:37)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
workbench.desktop.main.js:602  INFO UNRESPONSIVE extension host: starting to profile NOW
workbench.desktop.main.js:1964 Extension Host
workbench.desktop.main.js:1964 Debugger attached.
workbench.desktop.main.js:602  WARN UNRESPONSIVE extension host: 'p403n1x87.austin-vscode' took 99% of 5678.548ms, saved PROFILE here: 'file:///c%3A/Users/sterg/AppData/Local/Temp/exthost-6f65b4.cpuprofile' Array(3)
workbench.desktop.main.js:86 [Extension Host] rejected promise not handled within 1 second: Error: cannot open file:///%3Cfrozen%20importlib._bootstrap_external%3E. Detail: Unable to read file '\<frozen importlib._bootstrap_external>' (Error: Unable to resolve nonexistent file '\<frozen importlib._bootstrap_external>')
D @ workbench.desktop.main.js:86
workbench.desktop.main.js:86 [Extension Host] stack trace: Error: cannot open file:///%3Cfrozen%20importlib._bootstrap_external%3E. Detail: Unable to read file '\<frozen importlib._bootstrap_external>' (Error: Unable to resolve nonexistent file '\<frozen importlib._bootstrap_external>')
    at l.$tryOpenDocument (vscode-file://vscode-app/c:/Users/sterg/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2746:76700)
D @ workbench.desktop.main.js:86
workbench.desktop.main.js:602   ERR cannot open file:///%3Cfrozen%20importlib._bootstrap_external%3E. Detail: Unable to read file '\<frozen importlib._bootstrap_external>' (Error: Unable to resolve nonexistent file '\<frozen importlib._bootstrap_external>'): Error: cannot open file:///%3Cfrozen%20importlib._bootstrap_external%3E. Detail: Unable to read file '\<frozen importlib._bootstrap_external>' (Error: Unable to resolve nonexistent file '\<frozen importlib._bootstrap_external>')
    at l.$tryOpenDocument (vscode-file://vscode-app/c:/Users/sterg/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2746:76700)
workbench.desktop.main.js:602   ERR [Extension Host] Error: bad_status
    at c:\Users\sterg\.vscode\extensions\kiteco.kite-0.147.0\node_modules\kite-connector\lib\index.js:66:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```python
135workbench.desktop.main.js:sourcemap:602   ERR Invalid string length: RangeError: Invalid string length
    at Socket.<anonymous> (c:\Users\sterg\.vscode\extensions\p403n1x87.austin-vscode-0.10.8\out\providers\executor.js:47:37)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
30workbench.desktop.main.js:sourcemap:602   ERR Invalid string length: RangeError: Invalid string length
    at Socket.<anonymous> (c:\Users\sterg\.vscode\extensions\p403n1x87.austin-vscode-0.10.8\out\providers\executor.js:47:37)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

I'm rerunning it to get a fresh look at the logs (perusing the other "output" logs, I didn't see anything of value and there was a lot to sift through).

Here's what pulls up on the terminal starting afresh:
```
GitHub\sparks-baird\matbench-genmetrics\scripts\matbench_genmetrics_basic.py 

Starting Profiler in c:\Users\sterg\Documents\GitHub\sparks-baird\matbench-genmetrics.
Running '"C:\Program Files\P403n1x87\Austin\austin.exe"' with args '-i 100 --pipe  C:\Users\sterg\Miniconda3\envs\matbench-genmetrics\python.exe c:\Users\sterg\Documents\GitHub\sparks-baird\matbench-genmetrics\scripts\matbench_genmetrics_basic.py'.
```
And I'm using "wall time" with $100 \mu s$

**Comment by P403n1x87** [comment]
@sgbaird Austin doesn't save the samples when running the `Profile with Austin` command, it pipes the output directly to the extension for visualisation. Raw sample files tend to be quite big so they are not persisted to avoid taking space on the file system. You can save the data by running the command

~~~ console
"C:\Program Files\P403n1x87\Austin\austin.exe"'-i 100 --pipe -o output.austin  C:\Users\sterg\Miniconda3\envs\matbench-genmetrics\python.exe c:\Users\sterg\Documents\GitHub\sparks-baird\matbench-genmetrics\scripts\matbench_genmetrics_basic.py
~~~

directly in the terminal, which will then save the samples in `output.austin` within the working directory. If opening this file with the extension results in the same garbled UI, then perhaps it's worth reinstalling the extension, or trying a previous version. But please do attach the file to the issue so that I can try to reproduce the problem on my end and see if it can be fixed.

**Comment by P403n1x87** [comment]
Closing for lack of activity for now. If this is still an issue please feel free to re-open.
